// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1RvNoXuyl7W1xAtBLqNvVXv3hZVawsA8',
    appId: '1:735781746905:web:1d81f58c58ecc3bfb7a6c8',
    messagingSenderId: '735781746905',
    projectId: 'trustcam-9095a',
    authDomain: 'trustcam-9095a.firebaseapp.com',
    storageBucket: 'trustcam-9095a.firebasestorage.app',
    measurementId: 'G-XKGBSXMBQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-_zk9XdgR9TTeR2TyIJY6leqqOoe8bB4',
    appId: '1:735781746905:android:5158ed8b8c29cdb6b7a6c8',
    messagingSenderId: '735781746905',
    projectId: 'trustcam-9095a',
    storageBucket: 'trustcam-9095a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmRaEnLEUAFdzyxRwPaaR9HZX40a1Ug_s',
    appId: '1:735781746905:ios:c50b446c7138e8dab7a6c8',
    messagingSenderId: '735781746905',
    projectId: 'trustcam-9095a',
    storageBucket: 'trustcam-9095a.firebasestorage.app',
    iosBundleId: 'com.example.trustcamapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmRaEnLEUAFdzyxRwPaaR9HZX40a1Ug_s',
    appId: '1:735781746905:ios:c50b446c7138e8dab7a6c8',
    messagingSenderId: '735781746905',
    projectId: 'trustcam-9095a',
    storageBucket: 'trustcam-9095a.firebasestorage.app',
    iosBundleId: 'com.example.trustcamapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1RvNoXuyl7W1xAtBLqNvVXv3hZVawsA8',
    appId: '1:735781746905:web:4916372cbf6380eeb7a6c8',
    messagingSenderId: '735781746905',
    projectId: 'trustcam-9095a',
    authDomain: 'trustcam-9095a.firebaseapp.com',
    storageBucket: 'trustcam-9095a.firebasestorage.app',
    measurementId: 'G-DWR9NC11H8',
  );
}
